true_data = {
    "After Berial is defeated, he will revive himself from the position where a non-summoned enemy is defeated.": True,
    "Arden is one of the Three Sages in the Dark Forest.": True,
    "Bryon has a falcon comapnion named Elona.": True,
    "Carolina's snowballs will attack enemies imprisoned by Confining Spell.": True,
    "Cassadee greatly admires Merlin, the legendary mage.": True,
    "Cats in Holistone will walk away in annoyance if you interact with them too often.": True,
    "Dionel once cast his spear toward Hoistone to kill a golem.": True,
    "Dream Realm Bosses have multiple difficulties, and they cannot be defeated in Endless Mode.": True,
    "Due to faction Strategies wilder heroes can do more damage to graveborn heroes.": True,
    "Each Artifact has its unique support effects.": True,
    "Each challenge in Honor Duel ends after you achieve 9 wins or take 3 losses.": True,
    "Florabelle is a teacher at Jade Lake Academy (unsure about wording) works as a teacher, vaduso mountains.": True,
    "Golems are powered by an energy core inside of them.": True,
    "Golems used to be Dura's creations.": True,
    "Hewynn became friends with a hornleaf bear.": True,
    "Holistone was named after the Faith Stone it possessed, but it was later stolen.": True,
    "Honor Duel is a Fair Play mode where you can choose an initial formation (Artifact and heroes) to embark on a series of challenges.": True,
    "In Honor Duel, the Duel Store offers better items as its level increases, and you can level it up by completing more battles.": True,
    "In Honor Duel, you can sell your heroes in the Formation interface.": True,
    "Kruger has many skills that can weaken the enemies phys Def.": True,
    "Lady Vala refused to see Lord Franz once when he visited.": True,
    "Lord Franz tried to promote grape cultivation in Ryeham as a replacement for the existing wheat crops.": True,
    "Lyca, the captain of the Dusk Patrollers, has a younger brother.": True,
    "Marilee deals significantly less damage when enemies get close to her.": True,
    "Marilee often runs errands for the Evergreen Conservatory to support her family.": True,
    "Merlin's ward cast upon Ryeham is actually a seal.": True,
    "Most units recover Energy after taking damage.": True,
    "Parisa likes to drink herbal tea.": True,
    "Rowan's first in line to take control of the Mithril Consortium.": True,
    "The Adamant Syndicate hired Shakir and his men to manage the camp.": True,
    "The Evergreen Conservatory has collected lots of golem materials.": True,
    "The Mirror Lake of Ryeham becomes frozen when the temperature drops.": True,
    "The Victory Rewards in Honor Duel refresh weekly.": True,
    "The aroma range of Smokey & Meerky will increase when their Ultimate is used.": True,
    "The blue butterflies are messengers of Misarte.": True,
    "The grapes promoted by Lord Franz can make gruglins go berserk.": True,
    "The head of Lunadorf is Granny Dahnie.": True,
    "The longer Scarlita stays in the air, the stronger she becomes.": True,
    "The place where Dolly threw the invites into the air was actually a balcony that belongs to Giga the Camelossus.": True,
    "There are different Bosses in Dream Realm.": True,
    "There are multiple difficulties in arcane labyrinth and you have to clear the previous one before you can do the next.": True,
    "There are three difficulties in Battle Drills. After clearing the easy drills, you then challenge the harder ones.": True,
    "Thoran's Resurrection skill can be triggered even when Thoran is defeated by instant kill effects.": True,
    "Under certain circumstances, Rhy's normale attacks can deal AoE damge.": True,
    "Valen is a member of the heroic order.": True,
    "Viperian needs to drain his own HP continuously to sustain the Darkvipers.": True,
    "We once met the legendary Dionel at the Moon Temple.": True,
    "When ascending a hero, you might need the Acorns of the hero's faction. You can use Omni-Acorns if you don't have enough acorns of the faction.": True,
    "When there are enemies with low HP on the battlefield, Seth will become stronger.": True,
    "While in a cave, you can tap the mini-map to find a button that lets you quickly return to its entrance": True,
    "You can chat with heroes by approaching certain tables and bonfires.": True,
    "You can equip your heroes with equipment in the Class Upgrade interface. The higher the equipment level, the greater the boost to your Power.": True,
    "You can obtain Pal-Coints for the first three Matched Gestures you perform with other players daily.": True,
    "You can one-shot some monsters without entering the battle if you're significantly stronger than them.": True,
    "You can only deploy heroes of the same faction in Legend Trial.": True,
    "You can tap the Camelossus icon on the mini-map to teleport to the Camelossus' location directly.": True,
    "You can unlock Exclusive Equipment and Exclusive Skills after ascending a hero to Mythic+": True,
    "You can unlock special skills after ascending a hero to Legendary+, Mythic+, and Supreme+": True,
    "You get a reward upon Reaching an Arena Tier for the first time.": True,
    "You have one free chance to collect Instant AFK rewards daily, each chance instantly grants rewards equal to 2 hours of AFK.": True,
    "You must defeat the Hypofiends of a map before you can explore it.": True,
    "Your combined title is made up of a prefix and a suffix. You are free to choose the prefix and suffix from your preferred title.": True
}

false_data = {
    "All normal attacks deal physical damage.": False,
    "Atalanta and Temesia are strangers to each other.": False,
    "Atalanta is a notorious thief.": False,
    "Berial's ability to revive himself can be triggered up to two times during a single battle.": False,
    "Both Parisa and Lyca are Dusk Patrollers.": False,
    "Both Valen and Temesia are Templar Knights.": False,
    "Bryon is Lorsans superior and both are Windwhisperers.": False,
    "Bryon's falcon, Elona, exists on the battlefield permanently.": False,
    "Carolina's Snowball Witchery can be used once every 5 seconds.": False,
    "Cassadee works as a teacher at the Serene Lyceum.": False,
    "Cassadee's Tidal Strength can increase her allies' ATK.": False,
    "Daily Rewards and Weekly Rewards in Arena are not affected by Arena Tier.": False,
    "Due to faction strategies, Mauler heroes can deal more damage to Lightbearer heroes.": False,
    "Eironn can stun the enemies with his Ultimate, Verdant Cyclone.": False,
    "Eironn, the Scion of the Vaduso, is well-loved by his people.": False,
    "Eomir has a longer beard than Arden.": False,
    "Eomir has a pair of Bunny ears on his head.": False,
    "Eomir is a prominent figure of the Wind Faction.": False,
    "Fay and Marilee were childhood friends.": False,
    "Fay graduated from the Serene Lyceum.": False,
    "Golems are commonly found in the Dark Forest.": False,
    "Granny Dahnie is Lorsan's Mentor.": False,
    "Hornleaf bears are commonly found in Golden Wheatshire.": False,
    "Illucia summoned Reinier with magic.": False,
    "In Battle Drills, heroes deployed cannot be swapped out.": False,
    "It costs stamina to initiate a battle in battle drill and your stamina will not be restored after using it up.": False,
    "Kafra is a loyal assistant to Eomir.": False,
    "Korin is a melee character with an attack range of 1 tile.": False,
    "Korin's prosthetic arms are made of quickvines by Granny Dahnie.": False,
    "Legend Trial features four towers that follow the same opening schedule.": False,
    "Lord Franz has a stocky build.": False,
    "Lorsan ate the wheat in the fields when you first met him.": False,
    "Lucius is a knight of the Heroic order.": False,
    "Mirael was once a comrade of Merlin.": False,
    "Rowan's pet is called Braddock.": False,
    "Scarlita holds a personal grudge against Berial.": False,
    "Temesia regrets letting Atalanta go.": False,
    "Temesia does not perform normal attacks, so increasing her ATK SPD is useless.": False,
    "Temesia will change her direction when she charges and reaches the edge of the battlefield. So, her charges are more frequent in small battlefields.": False,
    "Temesia's mount is a white deer.": False,
    "The Deerspirit Altar is located near the Lucent Tree in the Dark Forest.": False,
    "The Lucent Tree is situated in the northernmost part of the Dark Forest.": False,
    "The MIthiril Consortium is the mastermind behind the incident involving Lord Franz and the contaminated grapes.": False,
    "The arsonist of the fire in Ryeham is Mirael.": False,
    "The default critical damage multiplier is 200%.": False,
    "The score of Century Quest is determined by the highest number of taps you can achieve in a fixed amount of time.": False,
    "The villagers, intimidated by Mirael, refer to her as the Flame Sorceress.": False,
    "There are three temples in Remnant Peaks.": False,
    "There is a school named the Serene Lyceum to the northeast of Lovers' Wish.": False,
    "Valen belongs to a orginization called Fools.": False,
    "We have a familiar named Chippy. He is a mage.": False,
    "Weaver's real name is Scarlita.": False,
    "When Igor is on the battlefield, a tombstone will appear every time a character is defeated.": False,
    "When your formation contains 1 Wilder hero and 4 Lightbearer heroes, the Wilder Hero will not receive Faction Bonus for their stats.": False,
    "You can challenge other players to manual control battles in Arena.": False,
    "You can challenge the Dream Realm Bosses as many times as you want each day.": False,
    "You can participate in Battle Drills without joining a Guild.": False,
    "You can teleport to Waystones you have not visited before.": False,
    "You can use Forging Stones to forge equipment. The level of the equipment forged can exceed the Average Resonance Level.": False,
    "You cannot set your own defensive formation in Arena.": False
}